// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZGPhVItGxxeik_Wqi5kJTo8ygEkwqgyI',
    appId: '1:524550612610:web:84b819a3009b0c3f9b369b',
    messagingSenderId: '524550612610',
    projectId: 'notes-app-flutter-puffindev',
    authDomain: 'notes-app-flutter-puffindev.firebaseapp.com',
    storageBucket: 'notes-app-flutter-puffindev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMRXcgXVwnLtTTGEwrTezfIM3RkihAveE',
    appId: '1:524550612610:android:a172399ce0f697479b369b',
    messagingSenderId: '524550612610',
    projectId: 'notes-app-flutter-puffindev',
    storageBucket: 'notes-app-flutter-puffindev.appspot.com',
  );
}
